kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: {{ocp-namespace}}
  name: supplier-api-route
  labels:
    app: supplier-api
spec:
  to:
    kind: Service
    name: supplier-api-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
